# Site settings
title: Abdulsattar
email: asattar.md@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bimorphic.com" # the base hostname & protocol for your site
twitter_username: asattarmd
github_username: abdulsattar

# Build settings
gems:
  - jekyll-sitemap
permalink: /:title/
kramdown:
  input: GFM
  hard_wrap: false
sass:
  style: compressed
