# Site settings
title: Bimorphic
email: me@bimorphic.com
description: > # this means to ignore newlines until "baseurl:"
  Personal thoughts of Abdulsattar Mohammed on programming and software development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bimorphic.com" # the base hostname & protocol for your site
twitter_username: bimorphic
github_username:  abdulsattar

# Build settings
gems:
  - jekyll-sitemap
permalink: /:title/
kramdown:
  input: GFM
  hard_wrap: false
